version: "3"

services:
    nomi:
        image: itzg/minecraft-server:java8-multiarch
        volumes:
            - ./mc-data:/data
        env_file:
            - .env
        environment:
            EULA: "true"
            TYPE: AUTO_CURSEFORGE
            CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/nomi-ceu
            CF_FILENAME_MATCHER: "1.6"
            MEMORY: 6G
            ENABLE_WHITELIST: "true"
            OVERRIDE_WHITELIST: "true"
            ENFORCE_WHITELIST: "true"
            ONLINE_MODE: "false"
            ALLOW_FLIGHT: "true"


volumes:
    mc-data: {}
    
