# this does not work , yet 

version: "3"

services:
  mc:
    image: itzg/minecraft-server:java19
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.7.10
      GENERIC_PACK: "http://downloads.gtnewhorizons.com/ServerPacks/GT_New_Horizons_2.3.0_Server_Java_17-19.zip"
      FORGE_VERSION: "10.13.4.1614"
      MEMORY: "4G"
      EXTRA_ARGS: "@java9args.txt -Dfml.readTimeout=180"
      USE_MODPACK_START_SCRIPT: "false"

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./gtnh_server:/data
